[package]
name = "hermes-world"
version = {workspace = true}
edition = {workspace = true}

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
pinocchio = {workspace = true}
pinocchio-pubkey = {workspace = true}
pinocchio-system = {workspace = true}